Updated blank_secondary/refresh_secondary to check RAID (and not disk) size.
   - Now checks that the secondary disk is only not smaller than the size of
     the RAID on the primary disk (and not the size of that disk as it was
     previously checking) and hard exits if that is not the case.
   - Also updated the other checks in blank_secondary to align with those in
     refresh_secondary.
   - Remove any mention of '-v' option from the "blank_secondary -h" output.

diff --git a/RAID/blank_secondary b/RAID/blank_secondary
--- a/RAID/blank_secondary
+++ b/RAID/blank_secondary
@@ -1,7 +1,7 @@
 #!/bin/bash
 # For systems with GPT LVM RAID arrays, tries to reset everything on second disk
 
-usage() { echo "Usage: $0 [-A][-h]"; echo -e "  where\t-A\tAllow \"Secondary\" disk to be loaded at start"; echo -e " \t-v\tverbose (prompted) operation"; echo -e "  \t-h\tdisplay this help and exit"; }
+usage() { echo "Usage: $0 [-A][-h]"; echo -e "  where\t-A\tAllow \"Secondary\" disk to be loaded at start"; echo -e "  \t-h\tdisplay this help and exit"; }
 
 ACCEPT_LOAD=0
 VERBOSE=0
@@ -48,18 +48,22 @@ if grep "/boot/efi" /proc/mounts | grep -q "$disk"; then
 	mount /dev/sda1 /boot/efi
 fi
 
+# Perform sanity checks on secondary disk now that it's available
+if [ "$(cat /sys/block/$devname/removable)" != "0" ]; then
+	echo "ERROR: \"Secondary\" disk $disk is removable, check USB devices!!"
+	exit 1
+fi
 if mdadm --detail /dev/md0 | grep -q $disk; then
 	echo "ERROR: \"Secondary\" disk $disk is currently part of RAID /dev/md0!!"
 	exit 1
 fi
-
 if grep -q ^$disk /proc/mounts; then
 	echo "ERROR: Some part of \"Secondary\" disk $disk is mounted!!"
 	exit 1
 fi
-
-if [ $(cat /sys/block/sda/size) -gt $(cat /sys/block/$devname/size) ]; then
-	echo "WARNING: \"Secondary\" device $devname is smaller than sda"
+if [ $(cat /sys/block/md0/size) -gt $(cat /sys/block/$devname/size) ]; then
+	echo "ERROR: \"Secondary\" device $devname is too small to house RAID /dev/md0"
+	exit 1
 fi
 
 if [ $VERBOSE -eq 0 ]; then
diff --git a/RAID/refresh_secondary b/RAID/refresh_secondary
--- a/RAID/refresh_secondary
+++ b/RAID/refresh_secondary
@@ -78,10 +78,10 @@ if grep -q ^$disk /proc/mounts; then
 	echo "ERROR: Some part of \"Secondary\" disk $disk is mounted!!"
 	exit 1
 fi
-if [ $(cat /sys/block/sda/size) -gt $(cat /sys/block/$devname/size) ]; then
-	echo "WARNING: \"Secondary\" device $devname is smaller than sda"
-	echo -n "Continue anyway (Control-C aborts)?"
-	read $ans
+if [ $(cat /sys/block/md0/size) -gt $(cat /sys/block/$devname/size) ] ||
+    ([ -b $part2 ] && [ $(cat /sys/block/md0/size) -gt $(cat /sys/block/$devname/"$devname"2/size) ]); then
+	echo "ERROR: \"Secondary\" device $devname is too small to house RAID /dev/md0"
+	exit 1
 fi
 if ( [ $boot = "BIOS" ] && [ ! -z "$(sgdisk -i1 $disk | grep 'EFI System')" ] ) ||
    ( [ $boot = "EFI" ] && [ ! -z "$(sgdisk -i1 $disk | grep 'BIOS boot')" ] ); then
